/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/5.3.1/userguide/multi_project_builds.html
 */

rootProject.name = "prost"

include("loader")
project(":loader").buildFileName = "loader.gradle.kts"

include("query")
project(":query").buildFileName = "query.gradle.kts"
